### ISSUE TITLE
Calculate price for index token based on what was discussed

### ISSUE THREAD

**Issue by anhmt90** [anhmt90/thesis-index-token#6]
- [x] Index token price should be calculated based on what was discussed with Victor on May 05th, 2021 (see example below)

Price calculation example:
```

basket = all the component tokens 

basket = {DAI, LINK}
basketAMount = {amountDAI, amountLINK}
basketValue = amountDAI * 0.5 + amountLINK * 0.25


Uniswap:
	WETH /DAI= 0.5
	WETH/LINK= 0.25

==> IToken price = (amountDAI * 0.5 + amountLINK * 0.25) / amountIToken

circulation = 100 ITokens
initial basketValue = 1 eth
Itoken price = (1 DAI * 0.5 DAI/ETH  + 2 LINK * 0.25 LINK/ETH) / 100 = 0.01 eth


1 week later:
circulation = 100 ITokens
DAI/ETH = 0.25 ; LINK/ETH = 0.1
Itoken price = (1 DAI * 0.25 DAI/ETH  + 2 LINK * 0.1 LINK/ETH) / 100 = 0.0045 eth


minting new tokens
circulation = 150 ITokens

50 * 0.0045 is the price in eth the investor has to pay if he wanted to mint new Index tokens
Itoken price = (1 DAI * 0.25 DAI/ETH  + 2 LINK * 0.1 LINK/ETH) / 150 =  0.003 eth


totalSupply !== circulation
```

**Comment by anhmt90** [comment]
Based on what was discussed, Index tokens are mintable, meaning the total supply is dynamic. For this reason, the IndexToken contract itself should be an Ownable contract, with the ETF being the owner, which is the only entity with the right to mint new tokens. 

However, this comes at the cost of tight coupling between IndexToken and ETF contracts, which affect the maintainability of the ETF contract.  For instance, if we were to upgrade the ETF at some point in the future, then this would require us to deploy a new ETF contract with new desirable functionalities and to change the owner of the IndexToken at the same time. 
Of course, we could add a function in ETF contract that handle the owner changing, however, this again requires the owner privilege of the ETF's from an EOA. With this chain of ownership from EOA > ETF > IndexToken, the IndexToken contract is technically owned by an EOA, which looks dubious from investors' point of view. As a result, this approach of changing ownership for IndexToken contract is not really applicable. 

With that said, we come to the trade off between **mintability** of IndexToken and **maintainability** of ETF.

**Comment by vivowa** [comment]
> When investors purchase Index tokens, should the circulation be increased before or after the index price calculation? This will affect the price calculated.

The circulation should be increased _after_ the initial price calculation.
This way, the fair value is calculated in t=0 (buy) and in t+1 (issuance) both things happen a) investment in underlying basket as well as b) issuance of index token. Thus, both sides of the equation increase equally, and the fair price before and after the purchase stays equal.
